spring:
  datasource:
    username: root
    password: abc
    url: jdbc:mysql://localhost:3306/bbs
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 879798231@qq.com # 这里填写个人的qq邮箱
    password: rdxungqedajpbeba # 注：这里不是qq邮箱的密码，而是授权码
    default-encoding: UTF-8
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mail:
  fromMail:
    addr: 879798231@qq.com
    
logging: 
  level:
    com:
      jt: debug
server:
  port: 80